---
- name: Windows Disk Cleanup
  hosts: all
  strategy: free
  serial: 25
  gather_facts: yes
  become: yes
  become_method: runas
  become_user: SYSTEM
  vars:
    cleanmgr_install_path: C:/Windows/System32/cleanmgr.exe
#    cleanmgr_sagerun: "0001"

  tasks:

  - name: "Remove Temp Files older than 30 days" 
    win_shell: $tempfolders = @("C:\Windows\Temp\*", "C:\Windows\Prefetch\*", "C:\Documents and Settings\*\Local Settings\temp\*", "C:\Users\*\Appdata\Local\Temp\*"); Get-ChildItem  $tempfolders -Recurse | Where-Object {$_.LastWriteTime -lt (Get-Date).AddDays(-30)} | Remove-Item -Force -Recurse
    args:
    register: deltmp_run
    ignore_errors: true
    tags:
    - quick
    - full
  - debug:
      var: deltmp_run
      #verbosity: 1

  - name: "Check for cleanmgr binary."
    win_stat:
      path: "{{ cleanmgr_install_path }}"
    register: cleanmgr_path
    tags:
    - quick
    - full
  - debug:
      var: cleanmgr_path
      #verbosity: 1

  - name: "Copy Cleanmgr from WinSxS Folder"
    win_shell: Get-ChildItem -Path C:\Windows\WinSxS\amd64* -Filter cleanmgr.exe -Recurse | Copy-Item -Destination C:\Windows\System32\ -Force; Get-ChildItem -Path C:\Windows\WinSxS\amd64* -Filter cleanmgr.exe.mui -Recurse | Copy-Item -Destination C:\Windows\System32\en-US\ -Force
    register: cleanmgr_install  
    when: not cleanmgr_path.stat.exists
    tags:
    - quick
    - full
  - debug:
    vars:
      cleanmgr_install
      cleanmgr_mui_install
    #verbosity: 1

  - name: "Check for existing cleanmgr binary (again)."
    win_stat:
      path: "{{ cleanmgr_install_path }}"
    register: cleanmgr_path
    tags:
    - quick
    - full
  - debug:
      var: cleanmgr_path
      #verbosity: 1

  # - name: "Enable all Options for Cleanmgr"
  #   win_shell: Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\*' | % {New-ItemProperty -Path $_.PSPath -Name StateFlags0001 -Value 2 -PropertyType DWord -Force};
  #   register: cleanmgr_regrun
  #   when: cleanmgr_path.stat.exists
  # - debug:
  #     var: cleanmgr_regrun
  #     #verbosity: 1

  - name: "Run Cleanmgr"
    # win_shell: "Start-Process -FilePath CleanMgr.exe -ArgumentList '/sagerun:0001' -WindowStyle Hidden -Wait"
    win_shell: "Start-Process -FilePath CleanMgr.exe -ArgumentList '/verylowdisk' -Wait"
    args:
      creates: "C:\\Windows\\Temp\\cleanmgr.log"
    register: cleanmgr_run
    when: cleanmgr_path.stat.exists
    tags:
    - quick
    - full
  - debug:
      var: cleanmgr_run
      #verbosity: 1

  - name: "Run DISM Cleanup"
    win_shell: "Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase"
    args:
      creates: "C:\\Windows\\Temp\\dismclean.log"
    register: dism_run
    tags:
    - never
    - full
  - debug:
      var: dism_run
      #verbosity: 1