---
- name: Windows Disk Cleanup
  hosts: all
  strategy: free
  serial: 25
  gather_facts: yes
  become: yes
  become_method: runas
  become_user: SYSTEM
  vars:
    cleanmgr_install_path: C:/Windows/System32/cleanmgr.exe

  tasks:

  - name: Check for cleanmgr binary
    win_stat:
      path: "{{ cleanmgr_install_path }}"
    register: cleanmgr_path
    tags:
    - quick
    - full

  - name: Copy Cleanmgr from WinSxS Folder
    win_shell: Get-ChildItem -Path C:\Windows\WinSxS\amd64* -Filter cleanmgr.exe -Recurse | Copy-Item -Destination C:\Windows\System32\ -Force; Get-ChildItem -Path C:\Windows\WinSxS\amd64* -Filter cleanmgr.exe.mui -Recurse | Copy-Item -Destination C:\Windows\System32\en-US\ -Force
    register: cleanmgr_install  
    when: not cleanmgr_path.stat.exists
    tags:
    - quick
    - full

  - name: Check for existing cleanmgr binary (again)
    win_stat:
      path: "{{ cleanmgr_install_path }}"
    register: cleanmgr_path
    tags:
    - quick
    - full

  - name: Create temp dir
    ansible.windows.win_file:
      path: C:\ProgramData\ansible_tmp
      state: directory
    tags:
    - quick
    - full

  - name: Copy PsExec
    win_copy:
      src: ./PsExec.exe
      dest: c:\ProgramData\ansible_tmp\PsExec.exe
      force: no
    tags:
    - quick
    - full

  - name: Enable all Options for Cleanmgr
    win_shell: Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VolumeCaches\*' | % {New-ItemProperty -Path $_.PSPath -Name StateFlags0001 -Value 2 -PropertyType DWord -Force};
    register: cleanmgr_regrun
    when: cleanmgr_path.stat.exists
    tags:
    - quick
    - full

  - name: Run Cleanmgr
    win_psexec:
      executable: c:\ProgramData\ansible_tmp\PsExec.exe
      hostnames: "{{ ansible_host }}"
      elevated: true
      nobanner: true
      system: true
      interactive: true
      command: cleanmgr.exe /sagerun:1
    register: cleanmgr_run
    when: cleanmgr_path.stat.exists
    tags:
    - quick
    - full

  - name: Run DISM Cleanup
    win_shell: "Dism.exe /online /Cleanup-Image /StartComponentCleanup /ResetBase"
    register: dism_run
    tags:
    - never
    - full

  - name: Remove Temp Files older than 30 days
    win_shell: $tempfolders = @("C:\Windows\Temp\*", "C:\Windows\Prefetch\*", "C:\Documents and Settings\*\Local Settings\temp\*", "C:\Users\*\Appdata\Local\Temp\*"); Get-ChildItem  $tempfolders -Recurse | Where-Object {$_.LastWriteTime -lt (Get-Date).AddDays(-30)} | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
    args:
    register: deltmp_run
    ignore_errors: true
    failed_when: deltmp_run.rc > 1
    tags:
    - quick
    - full

  - name: Remove temp dir
    ansible.windows.win_file:
      path: c:\ProgramData\ansible_tmp
      state: absent
    tags:
    - quick
    - full
